name: CI — Heap Data Structures

on:
  push:
    branches: [ main, master, feature/** ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build, Test, and Benchmark
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Java 11 (Temurin)
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      # 3️⃣ Build and run tests
      - name: Build with Maven
        run: mvn -B clean verify

      # 4️⃣ Run short JMH benchmark test (dry run)
      - name: Run Benchmarks (short dry run)
        run: |
          echo "Running short benchmark..."
          java -jar target/assignment2-heap-1.0-SNAPSHOT.jar -wi 1 -i 1 -f 1 -bm avgt -tu ms || true

      # 5️⃣ Generate CSV benchmark results via CLI runner
      - name: Run CLI benchmark runner
        run: |
          mkdir -p docs/benchmarks
          java -cp target/assignment2-heap-1.0-SNAPSHOT.jar cli.BenchmarkRunner || true

      # 6️⃣ Upload benchmark CSV results
      - name: Upload benchmark CSVs
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: docs/benchmarks/

      # 7️⃣ Generate performance plots
      - name: Generate performance plots
        if: success()
        run: |
          python3 scripts/plot_benchmarks.py || true

      # 8️⃣ Upload performance plots as artifacts
      - name: Upload performance plots
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: performance-plots
          path: docs/performance-plots/
